settings:
  project_name: FortiSwitch ACL Manager
  switch_user: ""
  emergency_mode: false
  current_version: 2026.01.01.01
  switch_password: ""
api_keys: {}
restrictions:
  forbidden_networks: []
  forbidden_models:
  - S108FN
  - S108FP
  model_port_limits:
    '108': 8
    '248': 48
    '424': 24
    '448': 48
    DEFAULT_MAX: 48
campus: []
custom_services: []
standard_acl_policy: []
